### ISSUE TITLE
missing dlls reported when installing from built msi installer

### ISSUE THREAD

**Issue by rafalop** [cloudbase/ceph-windows-installer#23]
Hello, I am trying to build a new installer with patched ceph binaries.
I have succesfully built wnbd binaries, and ceph binaries.

I can also build the msi using the provided command in docs:
`msbuild ceph-windows-installer.sln /p:Platform=x64 /p:Configuration=Release`

The build reports a bunch of 'string overflow' warnings, but completes succesfully:
![image](https://user-images.githubusercontent.com/28511018/172303058-f24b814e-3009-4247-997f-5d15f7522a9d.png)

However when trying to run the msi to install, there complaints about missing dll files (seems 4 in total):
![image](https://user-images.githubusercontent.com/28511018/172303143-f2a2a908-6a1d-4fdf-a7a2-3bb001cc25d8.png)
![image](https://user-images.githubusercontent.com/28511018/172303157-33430d5d-d122-4de9-a9ce-c52e892b3660.png)
![image](https://user-images.githubusercontent.com/28511018/172303180-0e875d8b-b9bb-4f90-89f0-cb6596db2994.png)
![image](https://user-images.githubusercontent.com/28511018/172303596-ab80a1a7-3be1-4d36-8592-0045d270ca0a.png)

I inspected the produced msi and these missing DLLs appear to be present (inside cab3.cab), however they are somehow not detected/used during the installation.

**Comment by ionutbalutoiu** [comment]
Hello @rafalop,

I just built a new MSI with the `Build.ps1` script from the root directory of this repo:
```
.\Build.ps1 -CephZipPath C:\Users\Administrator\Desktop\ceph.zip
```

Everything went fine on my side:

<img width="517" alt="install_msi" src="https://user-images.githubusercontent.com/6170274/172437778-a984b90b-5966-4165-8343-9b7924c69ad3.png">
<img width="717" alt="cli_versions" src="https://user-images.githubusercontent.com/6170274/172437851-e7885764-bdfb-49d7-838d-40764e5cf206.png">

The machine that I'm using has only the Ceph on Windows installed:

<img width="951" alt="control_panel_programs" src="https://user-images.githubusercontent.com/6170274/172437929-531dbab2-35c5-4b17-b0ef-3f31d5311d32.png">

Can you please share more info about your Visual Studio build environment ?

These are the parameters that I used to do an unattended installation of Visual Studio 2019:
https://github.com/ceph/ceph-build/blob/33989bae4b4e23f86587c50964058b5b80e40ba1/ceph-windows-image-build/build/setup.ps1#L82-L89

**Comment by rafalop** [comment]
I have used the 'copy info' in the 'about' section of visual studio 2019 to capture the environment. 

I tried using the docker image, but that did not work it failed I believe installing the wdk in the container but there is not enough info to work out why (you try to run the same command manually in the container and there is no output). I also tried the unattended script, as it also generated an error, so that is why I had turned to a manual build.

But I see that you made a commit on it overnight, so I will try running that setup.ps1 from the wnbd repo that you pasted in your reply, and then build.ps1 from this repo to see if that works.

[visual_studio_info.txt](https://github.com/cloudbase/ceph-windows-installer/files/8857171/visual_studio_info.txt)

**Comment by rafalop** [comment]
sorry, just realised that was from the ceph repo not from wnbd repo. i didn't know there was a fully automated kvm end to end build process in the ceph repo, this is undocumented!

**Comment by rafalop** [comment]
i tried running the setup.ps1 script on my machine, and was able to run build.ps1 afterwards. The messages of missing DLLs are now gone, however installing the resultant msi still throws an error:
![image](https://user-images.githubusercontent.com/28511018/172526467-6c7e8d0e-cfe2-44aa-a6f7-18d68501167e.png)

I then tried starting from scratch using the ceph-build repo builder here: https://github.com/ceph/ceph-build/tree/main/ceph-windows-installer-build/build. This successfully creates a windows box and installs the prerequisites. I then git clone this repo, and try build.ps1, but the result is exactly the same as above.

I have uploaded the failed msi installer log in case that can help diagnose this problem. This is the only thing I see in that log:
```
CustomActions: Running command: "C:\Program Files\Ceph\bin\wnbd-client.exe" install-driver "C:\Program Files\Ceph\driver\\wnbd.inf"
MSI (s) (50!FC) [15:27:00:363]: Product: Ceph for Windows -- Failed to install the Windows Ceph RBD WNBD driver. A reboot might be required. Check the MSI log for more details.

Failed to install the Windows Ceph RBD WNBD driver. A reboot might be required. Check the MSI log for more details.
CustomActions: Command failed. Return value: -1073741515
```

[log.txt](https://github.com/cloudbase/ceph-windows-installer/files/8858130/log.txt)
.

**Comment by ionutbalutoiu** [comment]
> sorry, just realised that was from the ceph repo not from wnbd repo. i didn't know there was a fully automated kvm end to end build process in the ceph repo, this is undocumented!

The KVM E2E workflow is submitted for Ceph CI/CD purposes.

However, you may use the scripts from there to setup your dev machine if you want.

> Failed to install the Windows Ceph RBD WNBD driver. A reboot might be required. Check the MSI log for more details.
> CustomActions: Command failed. Return value: -1073741515

Keep in mind that the installer built is unsigned (unless you used a valid SSL signing cert for Windows drivers).

This means, you have to enable test sign on your machine to be able to install it. Also, you should have secure boot disabled.
These are all documented as [wnbd prerequisites](https://github.com/cloudbase/wnbd#prerequisites-1).

**Comment by petrutlucian94** [comment]
Fwiw, "vcruntime140**d**" is the debug version, which isn't redistributable and is usually provided by Visual Studio. The error went away when using the "Build.ps1" script because it generates a release build, which uses the distributable runtime version.

Please let us know if you're still hitting errors after disabling secure boot and enabling self-signed drivers.

**Comment by rafalop** [comment]
@petrutlucian94 that makes sense, however i used `/p:Configuration=Release` when building. shouldn't that have used the redistributable runtime?

In any case, I was able to get this to work using setup.ps1 from the ceph-build repo, and then setting test signed drivers with bcdedit allowed the install to complete, thanks all.

do you have any guides/tips/links on creating the certificate so the driver can be signed? sorry i am completely new to building windows packages. I was looking at this, wondering if i will need anything other than what is output from the build. https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview

**Comment by ionutbalutoiu** [comment]
> @petrutlucian94 that makes sense, however i used `/p:Configuration=Release` when building. shouldn't that have used the redistributable runtime?

I suspect that your previous Visual Studio installation didn't have all the needed tools installed.

The `setup.ps1` script makes sure that Visual Studio is properly installed with all the necessary tools, so that's why I presume everything was properly bundled in the installer after that.

> do you have any guides/tips/links on creating the certificate so the driver can be signed? sorry i am completely new to building windows packages. I was looking at this, wondering if i will need anything other than what is output from the build. https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview

The `Build.ps1` script from this repository has extra parameters to take care of SSL signing:
https://github.com/cloudbase/ceph-windows-installer/blob/6d892550224f49b287bec09746359b03d4993167/Build.ps1#L27-L40

Behind the scenes, the script uses the `signtool.exe sign` (more info about it [here](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe#sign-command-options)) to do the actual code signing:
https://github.com/cloudbase/ceph-windows-installer/blob/6d892550224f49b287bec09746359b03d4993167/Build.ps1#L69-L78

Just to be clear, what you need to sign is:
1. The `wnbd` driver (which is bundled with the MSI package)
2. The actual MSI package (which is the build output of this `ceph-windows-installer` project)

So, `#1` needs to be done before building the MSI package, and `#2` needs to be done after building the MSI package.
The `Build.ps1` script takes care of both, if you provide the parameters for SSL signing.

You need a valid SSL certificate to sign Windows drivers (which can be used to sign the MSI package as well):
https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/signing-a-driver-for-public-release

**Comment by petrutlucian94** [comment]
I think the vc runtime concerns have been addressed and we can close the issue.
