### ISSUE TITLE
Installing ceph+dokan on my windows machine causes bluescreens on boot

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [cloudbase/ceph-windows-installer#30]
Installing dokan 1 and ceph qunicy causes my windows machine to bluescreen on every bootup, windows shows the erro code 0x0000225

It is not able to find or load windows\system32\winload.efi from the bootdrive anymore.

Windows 8.1

I was able to reproduce this 3 times, I don't know how to fix the boot process yet. Ceph was mounted and working before the reboot successfully. Reinstalling the whole OS and trying different things is my current way of debugging.
Any ideas?

**Comment by petrutlucian94** [comment]
Hi,

Thank you for opening this issue. We'll try to reproduce this as soon as possible. Just to make sure, you're using the latest Dokany 1 release, right? https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000

We got another bug report one week after dokany v1.5.1.1000 has been released https://github.com/cloudbase/ceph-windows-installer/issues/28, so there might be a connection.

For what is worth, we haven't tested Windows versions prior to Windows Server 2016 but I don't think this is necessarily the cause since the other issue mentions WS 2019.

Some other information that might help us reproduce the issue:

* you're mentioning dokany, has rbd been used at all?
* did you get to map a ceph filesystem before the crash?
* is there a crash dump available? It should be located at C:\Windows\Memory.dmp. In case of a VM, you may be able to attach the disk image to another VM or the host in order to retrieve the crash dump.
* is it crashing while or right after installing one of the MSIs? which one?

Thanks,
Lucian

**Comment by petrutlucian94** [comment]
I've just tried our latest quincy MSI and couldn't reproduce the issue.

I have the following:

```
ceph-dokan --version
ceph version 17.3.3 (a3ddd56e8213bca6c05819e00bec1ac31b7e98e5) quincy (stable)
```

dokan version: 1.5.1.1000 x64

I've used WS 2019 but I may give Windows 8.1 a go as well.

**Comment by petrutlucian94** [comment]
I've reproduced the issue on Windows 8.1. In fact, I've tried the following versions:

* windows 8.1, 10, 11
* windows server 2012 r2, 2016, 2019 and 2022

Windows 8.1, WS 2012 r2 and surprisingly WS 2016 fail to boot after installing the WNBD driver. The other newer releases work fine as long as secure boot is disabled.

We used to test WS 2016, so we'll try to figure out what's wrong. In the meantime, you could either use a different Windows release (if that's an option for you) or disable the WNBD (RBD) driver if you're only interested in cephfs.

**Comment by 0xFEEDC0DE64** [comment]
Ok thank you for trying, I really disklike any newer version than 8.1 (because of laggy right click menus and ads/notifications/forced updates), i will try without rbd as I don't need it. Thanks for finding this :)

**Comment by petrutlucian94** [comment]
Looks like the kernel socket initialization (WSK) fails on older Windows releases. For now, I've added a version check so that the WNBD driver refuses to install on unsupported Windows platforms: https://github.com/cloudbase/wnbd/pull/96.

We might eventually move the NBD client functionality out of the driver and have a separate userspace daemon (only used when connecting to NBD servers, not Ceph), which in theory would allow the driver to run on older Windows releases. However, we'll keep this hard requirement out of precaution since we can't commit to testing/supporting too many Windows releases.
